FROM golang:1.24-alpine AS builder

WORKDIR /build
COPY . .
RUN CGO_ENABLED=0 go build -ldflags "-s -w" -trimpath -o prom2parquet ./cmd/.

FROM alpine:latest

ARG TARGETARCH
RUN apk add --no-cache wget && \
    case ${TARGETARCH} in \
        "amd64")  DUMB_INIT_ARCH=x86_64  ;; \
        "arm64")  DUMB_INIT_ARCH=aarch64  ;; \
        *)        echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
    esac && \
    wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_${DUMB_INIT_ARCH} && \
    chmod +x /usr/local/bin/dumb-init && \
    apk del wget

COPY --from=builder /build/prom2parquet /prom2parquet

ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]
